### ISSUE TITLE
Bug: 4.4.9 invalid argument

### ISSUE THREAD

**Issue by bergerar** [contao/comments-bundle#10]
$arrOptions is passed to Contao\Model::isPreviewMode(array $arrOptions), but $arrOptions isn't set in this function.

`Type error: Argument 1 passed to Contao\Model::isPreviewMode() must be of the type array, null given, called in \vendor\contao\comments-bundle\src\Resources\contao\models\CommentsModel.php on line 149`

PHP 7.1

**Comment by fritzmg** [comment]
Duplicate of #9
