### ISSUE TITLE
Different behaviour from local to remote environment

### ISSUE THREAD

**Issue by agenceaddictic** [contao/comments-bundle#17]
I'm trying to build a custom module by overwriting Contao's comments module.

In localhost so far so good. But, when i push to remote, Contao's comments module seems to be called after my custom module and so my module isn't rendered anymore. (I detected call order with var_dumps).

Why Contao's comments module is called after mine ? Can we change the module call order ?

Thx everyone !!

**Comment by fritzmg** [comment]
Yes, you can do that via the contao manager plugin in the managed edition:
```php
    /**
     * {@inheritdoc}
     */
    public function getBundles(ParserInterface $parser): array
    {
        return [
            BundleConfig::create(MyBundle::class)
                ->setLoadAfter([
                    ContaoCommentsBundle::class
                ]),
        ];
    }
```
