### ISSUE TITLE
Enhancement FE Comments form

### ISSUE THREAD

**Issue by ghost** [contao/comments-bundle#4]
<a href="https://github.com/Anke"><img src="https://avatars3.githubusercontent.com/u/1300920?v=3" align="left" width="42" height="42"></img></a> [Issue](https://github.com/contao/core-bundle/issues/830) by @Anke
May 18th, 2017, 14:30 GMT

1. Would be nice if the FE comments form had a title by default. 
2. All confirmation messages are naturally displayed within the form element which by default is at the far bottom of the page, i.e. messages like "your comment wil be published ..." or messages concerning subsciptions often won't be found by users. Is there a solution to this problem?

**Comment by leofeyer** [comment]
Meanwhile implemented.
