### ISSUE TITLE
Associate comments with members

### ISSUE THREAD

**Issue by m-vo** [contao/comments-bundle#5]
Currently there is no way to find out which comment was posted by which member even if comments are only allowed after login. That disallows linking profiles, showing avatars etc. or even showing the selected comments to the user itself (like in a dashboard).

Of course a way around this problem is to write a custom extension that adds a ``author_member`` or something column and uses the ``addComment`` hook to update the data. Imho this should be the case by default 😄 - there is an ``author`` column anyway (for BE users?).

What do you think?

**Comment by m-vo** [comment]
Any concerns with this idea or too special? Otherwise I'd make a pull request.

**Comment by leofeyer** [comment]
No concerns. 😃

**Comment by m-vo** [comment]
Allright. Do we want the member property just to be added to the database / template variables? Or should this be more of a feature that is also visible in the BE (or even the default template)? If we want the latter one we would first have to decide a few things. For instance how to deal with the redundant or possibly conflicting user data (form field / user entry) or how to circumvent that and some more details.

**Comment by m-vo** [comment]
closed in favor of #7
