### ISSUE TITLE
Kommentarfunktion evtl. andere Reihenfolge

### ISSUE THREAD

**Issue by ghost** [contao/comments-bundle#6]
Will den vorletzten Post aufgreifen/erweitern:
Könnte man die bereits abgegebenen Kommentare nicht **über** die Überschrift "einen Kommentar abgeben" stellen und mit einer eigenen Überschrift wie z.B. "abgegebene Kommentare" o.ä. versehen? Ich empfinde es jetzt als unlogisch, wenn nach "einen Kommentar abgeben" erst einmal die schon veröffentlichten Kommentare kommen und erst danach das Formular für neue Kommentare.

**Comment by Aybee** [comment]
Ja, das fand ich auch schon immer komisch.

ps Ich sehe hier keinen vorletzten Post. Deiner ist bei mir der erste.

**Comment by ghost** [comment]
Ich meinte das vorletzte "Issue"...

**Comment by Aybee** [comment]
Und warum verlinkst du es nicht?

**Comment by ghost** [comment]
Mensch, ich bin froh, hier überhaupt was zu finden...

**Comment by leofeyer** [comment]
Ich finde es nicht unlogisch, dass das Formular am Ende steht. Wir zeigen ja die Kommentare von alt nach neu an, daher steht das Formular auch da, wo der Kommentar später steht.

**Comment by Aybee** [comment]
Ich denke, dass das Formular am Ende steht ist ok, auch für @jewo5. Es geht hier um die Überschriften. Hier mal ein modifiziertes Layout von contao.org so wie wir es uns vorstellen.
![bildschirmfoto am 2017-08-03 um 22 03 50](https://user-images.githubusercontent.com/1143013/28941328-fa859460-7897-11e7-9b47-a271d0c55c5e.png)

**Comment by ghost** [comment]
Ja, ganz genau so frickel ich mir das auch immer so hin und das das Formular ganz unten steht, wäre für mich richtig - so wie der Screenshot aussieht würde ich es als logisch empfinden - perfekt, danke dir!

**Comment by leofeyer** [comment]
Implementiert in 9ee67d734e1e44adc04e4ceb5365f05ec270ed14.
