### ISSUE TITLE
Contao\Model::isPreviewMode() must be of the type array, null given

### ISSUE THREAD

**Issue by skolarianer** [contao/comments-bundle#9]
```
Type error: Argument 1 passed to Contao\Model::isPreviewMode() must be of the type array, null given, called in …/vendor/contao/comments-bundle/src/Resources/contao/models/CommentsModel.php on line 149
```
Ich weiß leider nicht mehr woraufhin der Fehler auftrat. Entweder beim Update von 4.4.8 auf 4.4.9 oder beim Installieren einer Erweiterung.
Ich musste die Cookies löschen, um den Fehler loszuwerden.

EDIT: Sobald ich mich als FE_USER anmelde, taucht der Fehler wieder auf. Eine Anmeldung als FE_USER ist damit nicht mehr möglich. `comments-bundle` manuell zurück auf 4.4.8 und es geht wieder.

**Comment by leofeyer** [comment]
Siehe contao/core-bundle#1239.

**Comment by leofeyer** [comment]
Behoben in ddaa16e62501e1d04fa0bb0d12e26c8917947c80.
